const test=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {Pool}=require('pg');
const express=require('express');
const http=require('node:http');
const {Server}=require('socket.io');
const {io:clientIO}=require('socket.io-client');
const jwt=require('jsonwebtoken');

test('account security: persisted registration, cookies, CSRF, isolation, revocation, legacy rejection, admin and sockets', {skip:!process.env.TEST_DATABASE_URL},async()=>{
 const schema='account_security_'+Date.now();
 const admin=new Pool({connectionString:process.env.TEST_DATABASE_URL,ssl:{rejectUnauthorized:true}});
 await admin.query(`CREATE SCHEMA ${schema}`);
 const db=new Pool({connectionString:process.env.TEST_DATABASE_URL,ssl:{rejectUnauthorized:true},options:`-c search_path=${schema}`});
 const dbModule=require('../config/db');const original=dbModule.pool;dbModule.pool=db;
 process.env.NODE_ENV='production';process.env.APP_URL='https://test.example';process.env.JWT_SECRET='isolated-session-tests';
 let server,io,socket,roomId;
 try{
  await require('../utils/accounts').initAccounts(db);
  const auth=require('../middleware/auth');
  const app=express();app.use(auth.csrfGuard);app.use(express.json());
  app.use('/auth',require('./auth'));app.use('/guest',require('./guest'));
  app.use('/rooms',require('./rooms'));
  app.post('/admin',auth.authenticateToken,auth.requireAdmin,(req,res)=>res.json({ok:true}));
  server=http.createServer(app);io=new Server(server,{allowRequest:(req,done)=>done(null,auth.allowedSocketRequest(req.headers))});app.set('io',io);
  require('../socket/handler').setupSocket(io);
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
  async function call(path,body,cookie='',method,extra={}){const res=await fetch(base+path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json','X-YTM-Request':'1',Origin:'https://test.example',Cookie:cookie,...extra},...(body?{body:JSON.stringify(body)}:{})});const text=await res.text();return {status:res.status,data:text?JSON.parse(text):null,cookie:res.headers.get('set-cookie')?.split(';')[0],rawCookie:res.headers.get('set-cookie')};}
  const password='a';
  assert.equal(auth.allowedSocketRequest({'sec-fetch-site':'same-origin'}),true);
  assert.equal(auth.allowedSocketRequest({origin:'https://evil.example','sec-fetch-site':'same-origin'}),false);
  assert.equal(auth.allowedSocketRequest({'sec-fetch-site':'cross-site'}),false);
  assert.equal(auth.allowedSocketRequest({}),false);
  assert.equal((await call('/auth/register',{username:'Empty',password:''})).status,400);
  assert.equal((await call('/auth/register',{username:'CSRF',password},'','POST',{Origin:'https://evil.example'})).status,403);
  const first=await call('/auth/register',{username:'Ryuk',password});assert.equal(first.status,201);
  assert.match(first.rawCookie,/HttpOnly/);assert.match(first.rawCookie,/Secure/);assert.match(first.rawCookie,/SameSite=Lax/);
  assert.equal(first.data.user.isAdmin,false);assert.equal(first.data.user.publicId,'ytmt-01');assert.equal(first.data.token,undefined);
  const id=first.data.user.id;
  const row=(await db.query('SELECT * FROM accounts WHERE id=$1',[id])).rows[0];assert.notEqual(row.password_hash,password);assert.match(row.password_hash,/^scrypt\$/);
  assert.equal((await db.query('SELECT * FROM account_profiles WHERE id=$1',[id])).rowCount,1);
  const session=(await db.query('SELECT * FROM account_sessions WHERE account_id=$1',[id])).rows[0];assert.notEqual(session.token_hash,first.cookie.split('=')[1]);
  assert.equal((await call('/auth/register',{username:'RYUK',password})).status,409);
  assert.equal((await call('/auth/login',{username:'Ryuk',password:'wrong'})).status,401);
  const legacy=jwt.sign({userId:id,username:'Ryuk',type:'guest'},process.env.JWT_SECRET);
  assert.equal((await call('/guest/me',null,'',undefined,{Authorization:'Bearer '+legacy})).status,401);
  assert.equal((await call('/admin',{},first.cookie)).status,403);
  assert.equal((await call('/guest/profile',{field:'notes',value:'999'},first.cookie,'PATCH')).status,400);
  assert.equal((await call('/guest/profile',{field:'is_admin',value:'true'},first.cookie,'PATCH')).status,400);
  const image='data:image/webp;base64,UklGRiIAAABXRUJQVlA4IBYAAAAwAQCdASoBAAEADsD+JaQAA3AAAAAA';
  for(const [field,value]of [['bio','My biography'],['avatar_url',image],['cover_url',image],['display_name','New Ryuk']])assert.equal((await call('/guest/profile',{field,value},first.cookie,'PATCH')).status,200);
  const profile=(await call('/guest/profile',null,first.cookie)).data.profile;assert.equal(profile.bio,'My biography');assert.equal(profile.avatar_url,image);assert.equal(profile.cover_url,image);assert.equal(profile.display_name,'New Ryuk');
  assert.equal((await db.query('SELECT display_name FROM account_profiles WHERE id=$1',[id])).rows[0].display_name,'New Ryuk');
  const other=await call('/auth/register',{username:'Other',password});assert.equal((await call('/guest/profile',null,other.cookie)).data.profile.bio,'');
  const login=await call('/auth/login',{username:'New Ryuk',password});assert.equal(login.data.user.id,id);
  socket=clientIO(base,{transports:['polling'],reconnection:false,extraHeaders:{'Sec-Fetch-Site':'same-origin',Cookie:login.cookie}});
  await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);setTimeout(()=>reject(new Error('socket timeout')),5000).unref();});
  const created=await new Promise(r=>socket.emit('room:create',{name:'security-test'},r));assert.equal(created.success,true);roomId=created.room.id;
  const memberPath=`/rooms/${roomId}/members/${id}/profile`;
  assert.equal((await call(memberPath,null,other.cookie)).status,403);
  const memberProfile=await call(memberPath,null,login.cookie);assert.equal(memberProfile.status,200);
  assert.equal(memberProfile.data.profile.bio,'My biography');
  assert.equal(memberProfile.data.profile.password_hash,undefined);assert.equal(memberProfile.data.profile.token_hash,undefined);
  assert.equal((await call(`/rooms/${roomId}/members/${other.data.user.id}/profile`,null,login.cookie)).status,404);
  const disconnected=new Promise(r=>socket.once('disconnect',r));
  assert.equal((await call('/auth/password',{currentPassword:'wrong',password:'b'},first.cookie)).status,400);
  const changed=await call('/auth/password',{currentPassword:password,password:'b'},first.cookie);assert.equal(changed.status,200);
  await disconnected;
  assert.equal((await call('/auth/me',null,first.cookie)).status,401);assert.equal((await call('/auth/me',null,login.cookie)).status,401);
  assert.equal((await call('/auth/me',null,changed.cookie)).status,200);
  assert.equal((await call('/auth/logout',{},changed.cookie)).status,204);assert.equal((await call('/auth/me',null,changed.cookie)).status,401);
  const denied=clientIO(base,{transports:['websocket'],reconnection:false,auth:{token:legacy},extraHeaders:{Origin:'https://test.example'}});
  await new Promise((resolve,reject)=>{denied.once('connect',()=>reject(new Error('Legacy socket accepted')));denied.once('connect_error',resolve);setTimeout(()=>reject(new Error('legacy timeout')),5000).unref();});denied.close();
  const updated=await call('/auth/login',{username:'New Ryuk',password:'b'});assert.equal(updated.status,200);
  await db.query('UPDATE accounts SET is_admin=true WHERE id=$1',[id]);assert.equal((await call('/admin',{},updated.cookie)).status,200);
  await db.query('UPDATE account_sessions SET expires_at=now()-interval \'1 second\' WHERE account_id=$1',[id]);assert.equal((await call('/auth/me',null,updated.cookie)).status,401);
 }finally{socket?.close();if(io)await new Promise(r=>io.close(r));else if(server)await new Promise(r=>server.close(r));if(roomId)require('../utils/roomManager').deleteRoom(roomId);dbModule.pool=original;await db.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();await original.end();}
});
